### PR TITLE
Remove RHEL-7 support

### PR DESCRIPTION
**Pull request by comps**
(And a few related changes.)

### CODE REVIEW

**Review by mildas — COMMENTED** [review]
Regarding BackgroundHTPPServer changes, why didn't you change usages of BackgroundHTTPServer to `BackgroundHTTPServer(..., 0)` and left it with fixed ports?

**Comment by comps** [comment]
Because it would be more involved change (it would need some shuffling of code around, as you cannot pre-create URLs and other strings **before** a `with` context manager entry).

The current commit is frankly a left-over from me wanting to upgrade to a newer python version. ... If this PR is merged, I'll add a github issue about changing the ports.

**Comment by mildas** [comment]
@comps Okay, no problem with that. Please resolve conflicts and I will merge it

**Comment by comps** [comment]
Rebased to main, resolved the waiver conflict.

**Comment by comps** [comment]
Filed as https://github.com/RHSecurityCompliance/contest/issues/213

**Pull request merged**
