### PR TITLE
Misc small fixes in preparation for waives

### PR DESCRIPTION
**Pull request by comps**
Probably best to review this commit-by-commit.

### CODE REVIEW

**Comment by comps** [comment]
Actually let me move this back to Draft for a minute, it seems this caused some reporting bugs in Beaker.

**Comment by comps** [comment]
Sneaky operator precedence ...
```diff
-        'path': f'{status}: {name}' + f' ({note})' if note else '',
+        'path': f'{status}: {name}' + (f' ({note})' if note else ''),
```
Fixed now.

**Comment by comps** [comment]
Rebased to latest `main`.

**Review by cortesana — APPROVED** [review]
LGTM - Approved

**Pull request merged**
